/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as pluginsSpineRouteRouteImport } from './routes/(plugins)/spine/route'
import { Route as featuresPlannerRouteRouteImport } from './routes/(features)/planner/route'
import { Route as featuresPdfReaderRouteRouteImport } from './routes/(features)/pdf-reader/route'
import { Route as featuresFlashcardsRouteRouteImport } from './routes/(features)/flashcards/route'
import { Route as featuresDocumentsRouteRouteImport } from './routes/(features)/documents/route'
import { Route as pluginsExternalLinkViewIndexRouteImport } from './routes/(plugins)/external-link-view/index'
import { Route as featuresFlashcardsIndexRouteImport } from './routes/(features)/flashcards/index'
import { Route as featuresFlashcardsManageRouteImport } from './routes/(features)/flashcards/manage'
import { Route as featuresFlashcardsDeckIdRouteRouteImport } from './routes/(features)/flashcards/$deckId/route'
import { Route as featuresDocumentsDocumentIdRouteRouteImport } from './routes/(features)/documents/$documentId/route'
import { Route as featuresFlashcardsDeckIdIndexRouteImport } from './routes/(features)/flashcards/$deckId/index'
import { Route as featuresFlashcardsDeckIdStudyRouteImport } from './routes/(features)/flashcards/$deckId/study'

const pluginsSpineRouteRoute = pluginsSpineRouteRouteImport.update({
  id: '/(plugins)/spine',
  path: '/spine',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresPlannerRouteRoute = featuresPlannerRouteRouteImport.update({
  id: '/(features)/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresPdfReaderRouteRoute = featuresPdfReaderRouteRouteImport.update({
  id: '/(features)/pdf-reader',
  path: '/pdf-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresFlashcardsRouteRoute = featuresFlashcardsRouteRouteImport.update({
  id: '/(features)/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresDocumentsRouteRoute = featuresDocumentsRouteRouteImport.update({
  id: '/(features)/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const pluginsExternalLinkViewIndexRoute =
  pluginsExternalLinkViewIndexRouteImport.update({
    id: '/(plugins)/external-link-view/',
    path: '/external-link-view/',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresFlashcardsIndexRoute = featuresFlashcardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => featuresFlashcardsRouteRoute,
} as any)
const featuresFlashcardsManageRoute =
  featuresFlashcardsManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => featuresFlashcardsRouteRoute,
  } as any)
const featuresFlashcardsDeckIdRouteRoute =
  featuresFlashcardsDeckIdRouteRouteImport.update({
    id: '/$deckId',
    path: '/$deckId',
    getParentRoute: () => featuresFlashcardsRouteRoute,
  } as any)
const featuresDocumentsDocumentIdRouteRoute =
  featuresDocumentsDocumentIdRouteRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => featuresDocumentsRouteRoute,
  } as any)
const featuresFlashcardsDeckIdIndexRoute =
  featuresFlashcardsDeckIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => featuresFlashcardsDeckIdRouteRoute,
  } as any)
const featuresFlashcardsDeckIdStudyRoute =
  featuresFlashcardsDeckIdStudyRouteImport.update({
    id: '/study',
    path: '/study',
    getParentRoute: () => featuresFlashcardsDeckIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/documents': typeof featuresDocumentsRouteRouteWithChildren
  '/flashcards': typeof featuresFlashcardsRouteRouteWithChildren
  '/pdf-reader': typeof featuresPdfReaderRouteRoute
  '/planner': typeof featuresPlannerRouteRoute
  '/spine': typeof pluginsSpineRouteRoute
  '/documents/$documentId': typeof featuresDocumentsDocumentIdRouteRoute
  '/flashcards/$deckId': typeof featuresFlashcardsDeckIdRouteRouteWithChildren
  '/flashcards/manage': typeof featuresFlashcardsManageRoute
  '/flashcards/': typeof featuresFlashcardsIndexRoute
  '/external-link-view': typeof pluginsExternalLinkViewIndexRoute
  '/flashcards/$deckId/study': typeof featuresFlashcardsDeckIdStudyRoute
  '/flashcards/$deckId/': typeof featuresFlashcardsDeckIdIndexRoute
}
export interface FileRoutesByTo {
  '/documents': typeof featuresDocumentsRouteRouteWithChildren
  '/pdf-reader': typeof featuresPdfReaderRouteRoute
  '/planner': typeof featuresPlannerRouteRoute
  '/spine': typeof pluginsSpineRouteRoute
  '/documents/$documentId': typeof featuresDocumentsDocumentIdRouteRoute
  '/flashcards/manage': typeof featuresFlashcardsManageRoute
  '/flashcards': typeof featuresFlashcardsIndexRoute
  '/external-link-view': typeof pluginsExternalLinkViewIndexRoute
  '/flashcards/$deckId/study': typeof featuresFlashcardsDeckIdStudyRoute
  '/flashcards/$deckId': typeof featuresFlashcardsDeckIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(features)/documents': typeof featuresDocumentsRouteRouteWithChildren
  '/(features)/flashcards': typeof featuresFlashcardsRouteRouteWithChildren
  '/(features)/pdf-reader': typeof featuresPdfReaderRouteRoute
  '/(features)/planner': typeof featuresPlannerRouteRoute
  '/(plugins)/spine': typeof pluginsSpineRouteRoute
  '/(features)/documents/$documentId': typeof featuresDocumentsDocumentIdRouteRoute
  '/(features)/flashcards/$deckId': typeof featuresFlashcardsDeckIdRouteRouteWithChildren
  '/(features)/flashcards/manage': typeof featuresFlashcardsManageRoute
  '/(features)/flashcards/': typeof featuresFlashcardsIndexRoute
  '/(plugins)/external-link-view/': typeof pluginsExternalLinkViewIndexRoute
  '/(features)/flashcards/$deckId/study': typeof featuresFlashcardsDeckIdStudyRoute
  '/(features)/flashcards/$deckId/': typeof featuresFlashcardsDeckIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/documents'
    | '/flashcards'
    | '/pdf-reader'
    | '/planner'
    | '/spine'
    | '/documents/$documentId'
    | '/flashcards/$deckId'
    | '/flashcards/manage'
    | '/flashcards/'
    | '/external-link-view'
    | '/flashcards/$deckId/study'
    | '/flashcards/$deckId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/documents'
    | '/pdf-reader'
    | '/planner'
    | '/spine'
    | '/documents/$documentId'
    | '/flashcards/manage'
    | '/flashcards'
    | '/external-link-view'
    | '/flashcards/$deckId/study'
    | '/flashcards/$deckId'
  id:
    | '__root__'
    | '/(features)/documents'
    | '/(features)/flashcards'
    | '/(features)/pdf-reader'
    | '/(features)/planner'
    | '/(plugins)/spine'
    | '/(features)/documents/$documentId'
    | '/(features)/flashcards/$deckId'
    | '/(features)/flashcards/manage'
    | '/(features)/flashcards/'
    | '/(plugins)/external-link-view/'
    | '/(features)/flashcards/$deckId/study'
    | '/(features)/flashcards/$deckId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  featuresDocumentsRouteRoute: typeof featuresDocumentsRouteRouteWithChildren
  featuresFlashcardsRouteRoute: typeof featuresFlashcardsRouteRouteWithChildren
  featuresPdfReaderRouteRoute: typeof featuresPdfReaderRouteRoute
  featuresPlannerRouteRoute: typeof featuresPlannerRouteRoute
  pluginsSpineRouteRoute: typeof pluginsSpineRouteRoute
  pluginsExternalLinkViewIndexRoute: typeof pluginsExternalLinkViewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(plugins)/spine': {
      id: '/(plugins)/spine'
      path: '/spine'
      fullPath: '/spine'
      preLoaderRoute: typeof pluginsSpineRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/planner': {
      id: '/(features)/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof featuresPlannerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/pdf-reader': {
      id: '/(features)/pdf-reader'
      path: '/pdf-reader'
      fullPath: '/pdf-reader'
      preLoaderRoute: typeof featuresPdfReaderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/flashcards': {
      id: '/(features)/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof featuresFlashcardsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/documents': {
      id: '/(features)/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof featuresDocumentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(plugins)/external-link-view/': {
      id: '/(plugins)/external-link-view/'
      path: '/external-link-view'
      fullPath: '/external-link-view'
      preLoaderRoute: typeof pluginsExternalLinkViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/flashcards/': {
      id: '/(features)/flashcards/'
      path: '/'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof featuresFlashcardsIndexRouteImport
      parentRoute: typeof featuresFlashcardsRouteRoute
    }
    '/(features)/flashcards/manage': {
      id: '/(features)/flashcards/manage'
      path: '/manage'
      fullPath: '/flashcards/manage'
      preLoaderRoute: typeof featuresFlashcardsManageRouteImport
      parentRoute: typeof featuresFlashcardsRouteRoute
    }
    '/(features)/flashcards/$deckId': {
      id: '/(features)/flashcards/$deckId'
      path: '/$deckId'
      fullPath: '/flashcards/$deckId'
      preLoaderRoute: typeof featuresFlashcardsDeckIdRouteRouteImport
      parentRoute: typeof featuresFlashcardsRouteRoute
    }
    '/(features)/documents/$documentId': {
      id: '/(features)/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof featuresDocumentsDocumentIdRouteRouteImport
      parentRoute: typeof featuresDocumentsRouteRoute
    }
    '/(features)/flashcards/$deckId/': {
      id: '/(features)/flashcards/$deckId/'
      path: '/'
      fullPath: '/flashcards/$deckId/'
      preLoaderRoute: typeof featuresFlashcardsDeckIdIndexRouteImport
      parentRoute: typeof featuresFlashcardsDeckIdRouteRoute
    }
    '/(features)/flashcards/$deckId/study': {
      id: '/(features)/flashcards/$deckId/study'
      path: '/study'
      fullPath: '/flashcards/$deckId/study'
      preLoaderRoute: typeof featuresFlashcardsDeckIdStudyRouteImport
      parentRoute: typeof featuresFlashcardsDeckIdRouteRoute
    }
  }
}

interface featuresDocumentsRouteRouteChildren {
  featuresDocumentsDocumentIdRouteRoute: typeof featuresDocumentsDocumentIdRouteRoute
}

const featuresDocumentsRouteRouteChildren: featuresDocumentsRouteRouteChildren =
  {
    featuresDocumentsDocumentIdRouteRoute:
      featuresDocumentsDocumentIdRouteRoute,
  }

const featuresDocumentsRouteRouteWithChildren =
  featuresDocumentsRouteRoute._addFileChildren(
    featuresDocumentsRouteRouteChildren,
  )

interface featuresFlashcardsDeckIdRouteRouteChildren {
  featuresFlashcardsDeckIdStudyRoute: typeof featuresFlashcardsDeckIdStudyRoute
  featuresFlashcardsDeckIdIndexRoute: typeof featuresFlashcardsDeckIdIndexRoute
}

const featuresFlashcardsDeckIdRouteRouteChildren: featuresFlashcardsDeckIdRouteRouteChildren =
  {
    featuresFlashcardsDeckIdStudyRoute: featuresFlashcardsDeckIdStudyRoute,
    featuresFlashcardsDeckIdIndexRoute: featuresFlashcardsDeckIdIndexRoute,
  }

const featuresFlashcardsDeckIdRouteRouteWithChildren =
  featuresFlashcardsDeckIdRouteRoute._addFileChildren(
    featuresFlashcardsDeckIdRouteRouteChildren,
  )

interface featuresFlashcardsRouteRouteChildren {
  featuresFlashcardsDeckIdRouteRoute: typeof featuresFlashcardsDeckIdRouteRouteWithChildren
  featuresFlashcardsManageRoute: typeof featuresFlashcardsManageRoute
  featuresFlashcardsIndexRoute: typeof featuresFlashcardsIndexRoute
}

const featuresFlashcardsRouteRouteChildren: featuresFlashcardsRouteRouteChildren =
  {
    featuresFlashcardsDeckIdRouteRoute:
      featuresFlashcardsDeckIdRouteRouteWithChildren,
    featuresFlashcardsManageRoute: featuresFlashcardsManageRoute,
    featuresFlashcardsIndexRoute: featuresFlashcardsIndexRoute,
  }

const featuresFlashcardsRouteRouteWithChildren =
  featuresFlashcardsRouteRoute._addFileChildren(
    featuresFlashcardsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  featuresDocumentsRouteRoute: featuresDocumentsRouteRouteWithChildren,
  featuresFlashcardsRouteRoute: featuresFlashcardsRouteRouteWithChildren,
  featuresPdfReaderRouteRoute: featuresPdfReaderRouteRoute,
  featuresPlannerRouteRoute: featuresPlannerRouteRoute,
  pluginsSpineRouteRoute: pluginsSpineRouteRoute,
  pluginsExternalLinkViewIndexRoute: pluginsExternalLinkViewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
