/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as pluginsSpineRouteRouteImport } from './routes/(plugins)/spine/route'
import { Route as featuresPlannerRouteRouteImport } from './routes/(features)/planner/route'
import { Route as featuresPdfReaderRouteRouteImport } from './routes/(features)/pdf-reader/route'
import { Route as featuresFlashcardRouteRouteImport } from './routes/(features)/flashcard/route'
import { Route as featuresFlashcardIndexRouteImport } from './routes/(features)/flashcard/index'
import { Route as featuresFlashcardManageRouteImport } from './routes/(features)/flashcard/manage'
import { Route as featuresFlashcardDeckIdRouteRouteImport } from './routes/(features)/flashcard/$deckId/route'
import { Route as featuresFlashcardDeckIdIndexRouteImport } from './routes/(features)/flashcard/$deckId/index'
import { Route as featuresFlashcardDeckIdStudyRouteImport } from './routes/(features)/flashcard/$deckId/study'

const pluginsSpineRouteRoute = pluginsSpineRouteRouteImport.update({
  id: '/(plugins)/spine',
  path: '/spine',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresPlannerRouteRoute = featuresPlannerRouteRouteImport.update({
  id: '/(features)/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresPdfReaderRouteRoute = featuresPdfReaderRouteRouteImport.update({
  id: '/(features)/pdf-reader',
  path: '/pdf-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresFlashcardRouteRoute = featuresFlashcardRouteRouteImport.update({
  id: '/(features)/flashcard',
  path: '/flashcard',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresFlashcardIndexRoute = featuresFlashcardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => featuresFlashcardRouteRoute,
} as any)
const featuresFlashcardManageRoute = featuresFlashcardManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => featuresFlashcardRouteRoute,
} as any)
const featuresFlashcardDeckIdRouteRoute =
  featuresFlashcardDeckIdRouteRouteImport.update({
    id: '/$deckId',
    path: '/$deckId',
    getParentRoute: () => featuresFlashcardRouteRoute,
  } as any)
const featuresFlashcardDeckIdIndexRoute =
  featuresFlashcardDeckIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => featuresFlashcardDeckIdRouteRoute,
  } as any)
const featuresFlashcardDeckIdStudyRoute =
  featuresFlashcardDeckIdStudyRouteImport.update({
    id: '/study',
    path: '/study',
    getParentRoute: () => featuresFlashcardDeckIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/flashcard': typeof featuresFlashcardRouteRouteWithChildren
  '/pdf-reader': typeof featuresPdfReaderRouteRoute
  '/planner': typeof featuresPlannerRouteRoute
  '/spine': typeof pluginsSpineRouteRoute
  '/flashcard/$deckId': typeof featuresFlashcardDeckIdRouteRouteWithChildren
  '/flashcard/manage': typeof featuresFlashcardManageRoute
  '/flashcard/': typeof featuresFlashcardIndexRoute
  '/flashcard/$deckId/study': typeof featuresFlashcardDeckIdStudyRoute
  '/flashcard/$deckId/': typeof featuresFlashcardDeckIdIndexRoute
}
export interface FileRoutesByTo {
  '/pdf-reader': typeof featuresPdfReaderRouteRoute
  '/planner': typeof featuresPlannerRouteRoute
  '/spine': typeof pluginsSpineRouteRoute
  '/flashcard/manage': typeof featuresFlashcardManageRoute
  '/flashcard': typeof featuresFlashcardIndexRoute
  '/flashcard/$deckId/study': typeof featuresFlashcardDeckIdStudyRoute
  '/flashcard/$deckId': typeof featuresFlashcardDeckIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(features)/flashcard': typeof featuresFlashcardRouteRouteWithChildren
  '/(features)/pdf-reader': typeof featuresPdfReaderRouteRoute
  '/(features)/planner': typeof featuresPlannerRouteRoute
  '/(plugins)/spine': typeof pluginsSpineRouteRoute
  '/(features)/flashcard/$deckId': typeof featuresFlashcardDeckIdRouteRouteWithChildren
  '/(features)/flashcard/manage': typeof featuresFlashcardManageRoute
  '/(features)/flashcard/': typeof featuresFlashcardIndexRoute
  '/(features)/flashcard/$deckId/study': typeof featuresFlashcardDeckIdStudyRoute
  '/(features)/flashcard/$deckId/': typeof featuresFlashcardDeckIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/flashcard'
    | '/pdf-reader'
    | '/planner'
    | '/spine'
    | '/flashcard/$deckId'
    | '/flashcard/manage'
    | '/flashcard/'
    | '/flashcard/$deckId/study'
    | '/flashcard/$deckId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pdf-reader'
    | '/planner'
    | '/spine'
    | '/flashcard/manage'
    | '/flashcard'
    | '/flashcard/$deckId/study'
    | '/flashcard/$deckId'
  id:
    | '__root__'
    | '/(features)/flashcard'
    | '/(features)/pdf-reader'
    | '/(features)/planner'
    | '/(plugins)/spine'
    | '/(features)/flashcard/$deckId'
    | '/(features)/flashcard/manage'
    | '/(features)/flashcard/'
    | '/(features)/flashcard/$deckId/study'
    | '/(features)/flashcard/$deckId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  featuresFlashcardRouteRoute: typeof featuresFlashcardRouteRouteWithChildren
  featuresPdfReaderRouteRoute: typeof featuresPdfReaderRouteRoute
  featuresPlannerRouteRoute: typeof featuresPlannerRouteRoute
  pluginsSpineRouteRoute: typeof pluginsSpineRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(plugins)/spine': {
      id: '/(plugins)/spine'
      path: '/spine'
      fullPath: '/spine'
      preLoaderRoute: typeof pluginsSpineRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/planner': {
      id: '/(features)/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof featuresPlannerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/pdf-reader': {
      id: '/(features)/pdf-reader'
      path: '/pdf-reader'
      fullPath: '/pdf-reader'
      preLoaderRoute: typeof featuresPdfReaderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/flashcard': {
      id: '/(features)/flashcard'
      path: '/flashcard'
      fullPath: '/flashcard'
      preLoaderRoute: typeof featuresFlashcardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(features)/flashcard/': {
      id: '/(features)/flashcard/'
      path: '/'
      fullPath: '/flashcard/'
      preLoaderRoute: typeof featuresFlashcardIndexRouteImport
      parentRoute: typeof featuresFlashcardRouteRoute
    }
    '/(features)/flashcard/manage': {
      id: '/(features)/flashcard/manage'
      path: '/manage'
      fullPath: '/flashcard/manage'
      preLoaderRoute: typeof featuresFlashcardManageRouteImport
      parentRoute: typeof featuresFlashcardRouteRoute
    }
    '/(features)/flashcard/$deckId': {
      id: '/(features)/flashcard/$deckId'
      path: '/$deckId'
      fullPath: '/flashcard/$deckId'
      preLoaderRoute: typeof featuresFlashcardDeckIdRouteRouteImport
      parentRoute: typeof featuresFlashcardRouteRoute
    }
    '/(features)/flashcard/$deckId/': {
      id: '/(features)/flashcard/$deckId/'
      path: '/'
      fullPath: '/flashcard/$deckId/'
      preLoaderRoute: typeof featuresFlashcardDeckIdIndexRouteImport
      parentRoute: typeof featuresFlashcardDeckIdRouteRoute
    }
    '/(features)/flashcard/$deckId/study': {
      id: '/(features)/flashcard/$deckId/study'
      path: '/study'
      fullPath: '/flashcard/$deckId/study'
      preLoaderRoute: typeof featuresFlashcardDeckIdStudyRouteImport
      parentRoute: typeof featuresFlashcardDeckIdRouteRoute
    }
  }
}

interface featuresFlashcardDeckIdRouteRouteChildren {
  featuresFlashcardDeckIdStudyRoute: typeof featuresFlashcardDeckIdStudyRoute
  featuresFlashcardDeckIdIndexRoute: typeof featuresFlashcardDeckIdIndexRoute
}

const featuresFlashcardDeckIdRouteRouteChildren: featuresFlashcardDeckIdRouteRouteChildren =
  {
    featuresFlashcardDeckIdStudyRoute: featuresFlashcardDeckIdStudyRoute,
    featuresFlashcardDeckIdIndexRoute: featuresFlashcardDeckIdIndexRoute,
  }

const featuresFlashcardDeckIdRouteRouteWithChildren =
  featuresFlashcardDeckIdRouteRoute._addFileChildren(
    featuresFlashcardDeckIdRouteRouteChildren,
  )

interface featuresFlashcardRouteRouteChildren {
  featuresFlashcardDeckIdRouteRoute: typeof featuresFlashcardDeckIdRouteRouteWithChildren
  featuresFlashcardManageRoute: typeof featuresFlashcardManageRoute
  featuresFlashcardIndexRoute: typeof featuresFlashcardIndexRoute
}

const featuresFlashcardRouteRouteChildren: featuresFlashcardRouteRouteChildren =
  {
    featuresFlashcardDeckIdRouteRoute:
      featuresFlashcardDeckIdRouteRouteWithChildren,
    featuresFlashcardManageRoute: featuresFlashcardManageRoute,
    featuresFlashcardIndexRoute: featuresFlashcardIndexRoute,
  }

const featuresFlashcardRouteRouteWithChildren =
  featuresFlashcardRouteRoute._addFileChildren(
    featuresFlashcardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  featuresFlashcardRouteRoute: featuresFlashcardRouteRouteWithChildren,
  featuresPdfReaderRouteRoute: featuresPdfReaderRouteRoute,
  featuresPlannerRouteRoute: featuresPlannerRouteRoute,
  pluginsSpineRouteRoute: pluginsSpineRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
